modLoader="javafml"
loaderVersion="[39,)"
license="GPL3"

[[mods]]
modId="framework"
version="0.2.2"
displayName="Framework"
updateJSONURL="https://mrcrayfish.com/modupdatejson?id=framework"
displayURL="https://mrcrayfish.com/mods?id=framework"
logoFile="framework.png"
authors="MrCrayfish"
description="A library providing powerful utilities for developers"

[[dependencies.framework]]
    modId="forge"
    mandatory=true
    versionRange="[39.0.45,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.framework]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1,1.19)"
    ordering="NONE"
    side="BOTH"
