package com.mrcrayfish.framework.api.sync;

import net.minecraft.resources.Identifier;
import net.minecraft.world.entity.*;
import net.minecraft.world.entity.ambient.AmbientCreature;
import net.minecraft.world.entity.ambient.Bat;
import net.minecraft.world.entity.animal.AgeableWaterCreature;
import net.minecraft.world.entity.animal.Animal;
import net.minecraft.world.entity.animal.allay.Allay;
import net.minecraft.world.entity.animal.armadillo.Armadillo;
import net.minecraft.world.entity.animal.axolotl.Axolotl;
import net.minecraft.world.entity.animal.bee.Bee;
import net.minecraft.world.entity.animal.camel.Camel;
import net.minecraft.world.entity.animal.camel.CamelHusk;
import net.minecraft.world.entity.animal.chicken.Chicken;
import net.minecraft.world.entity.animal.cow.AbstractCow;
import net.minecraft.world.entity.animal.cow.Cow;
import net.minecraft.world.entity.animal.cow.MushroomCow;
import net.minecraft.world.entity.animal.dolphin.Dolphin;
import net.minecraft.world.entity.animal.equine.*;
import net.minecraft.world.entity.animal.feline.Cat;
import net.minecraft.world.entity.animal.feline.Ocelot;
import net.minecraft.world.entity.animal.fish.*;
import net.minecraft.world.entity.animal.fox.Fox;
import net.minecraft.world.entity.animal.frog.Frog;
import net.minecraft.world.entity.animal.frog.Tadpole;
import net.minecraft.world.entity.animal.goat.Goat;
import net.minecraft.world.entity.animal.golem.AbstractGolem;
import net.minecraft.world.entity.animal.golem.CopperGolem;
import net.minecraft.world.entity.animal.golem.IronGolem;
import net.minecraft.world.entity.animal.golem.SnowGolem;
import net.minecraft.world.entity.animal.happyghast.HappyGhast;
import net.minecraft.world.entity.animal.nautilus.Nautilus;
import net.minecraft.world.entity.animal.nautilus.ZombieNautilus;
import net.minecraft.world.entity.animal.panda.Panda;
import net.minecraft.world.entity.animal.parrot.Parrot;
import net.minecraft.world.entity.animal.parrot.ShoulderRidingEntity;
import net.minecraft.world.entity.animal.pig.Pig;
import net.minecraft.world.entity.animal.polarbear.PolarBear;
import net.minecraft.world.entity.animal.rabbit.Rabbit;
import net.minecraft.world.entity.animal.sheep.Sheep;
import net.minecraft.world.entity.animal.sniffer.Sniffer;
import net.minecraft.world.entity.animal.squid.GlowSquid;
import net.minecraft.world.entity.animal.squid.Squid;
import net.minecraft.world.entity.animal.turtle.Turtle;
import net.minecraft.world.entity.animal.wolf.Wolf;
import net.minecraft.world.entity.boss.enderdragon.EndCrystal;
import net.minecraft.world.entity.boss.enderdragon.EnderDragon;
import net.minecraft.world.entity.boss.wither.WitherBoss;
import net.minecraft.world.entity.decoration.*;
import net.minecraft.world.entity.decoration.painting.Painting;
import net.minecraft.world.entity.item.FallingBlockEntity;
import net.minecraft.world.entity.item.ItemEntity;
import net.minecraft.world.entity.item.PrimedTnt;
import net.minecraft.world.entity.monster.*;
import net.minecraft.world.entity.monster.breeze.Breeze;
import net.minecraft.world.entity.monster.creaking.Creaking;
import net.minecraft.world.entity.monster.hoglin.Hoglin;
import net.minecraft.world.entity.monster.illager.*;
import net.minecraft.world.entity.monster.piglin.AbstractPiglin;
import net.minecraft.world.entity.monster.piglin.Piglin;
import net.minecraft.world.entity.monster.piglin.PiglinBrute;
import net.minecraft.world.entity.monster.skeleton.*;
import net.minecraft.world.entity.monster.spider.CaveSpider;
import net.minecraft.world.entity.monster.spider.Spider;
import net.minecraft.world.entity.monster.warden.Warden;
import net.minecraft.world.entity.monster.zombie.Drowned;
import net.minecraft.world.entity.monster.zombie.Husk;
import net.minecraft.world.entity.monster.zombie.Zombie;
import net.minecraft.world.entity.monster.zombie.ZombieVillager;
import net.minecraft.world.entity.monster.zombie.ZombifiedPiglin;
import net.minecraft.world.entity.npc.villager.AbstractVillager;
import net.minecraft.world.entity.npc.villager.Villager;
import net.minecraft.world.entity.npc.wanderingtrader.WanderingTrader;
import net.minecraft.world.entity.player.Player;
import net.minecraft.world.entity.projectile.*;
import net.minecraft.world.entity.projectile.arrow.AbstractArrow;
import net.minecraft.world.entity.projectile.arrow.Arrow;
import net.minecraft.world.entity.projectile.arrow.SpectralArrow;
import net.minecraft.world.entity.projectile.arrow.ThrownTrident;
import net.minecraft.world.entity.projectile.hurtingprojectile.*;
import net.minecraft.world.entity.projectile.hurtingprojectile.windcharge.AbstractWindCharge;
import net.minecraft.world.entity.projectile.hurtingprojectile.windcharge.BreezeWindCharge;
import net.minecraft.world.entity.projectile.hurtingprojectile.windcharge.WindCharge;
import net.minecraft.world.entity.projectile.throwableitemprojectile.*;
import net.minecraft.world.entity.raid.Raider;
import net.minecraft.world.entity.vehicle.VehicleEntity;
import net.minecraft.world.entity.vehicle.boat.*;
import net.minecraft.world.entity.vehicle.minecart.*;

/**
 * Author: MrCrayfish
 */
public record SyncedClassKey<E extends Entity>(Class<E> entityClass, Identifier id)
{
    @Override
    public boolean equals(Object o)
    {
        if(this == o) return true;
        if(o == null || getClass() != o.getClass()) return false;
        SyncedClassKey<?> that = (SyncedClassKey<?>) o;
        return this.entityClass.getName().equals(that.entityClass.getName());
    }

    @Override
    public int hashCode()
    {
        return this.entityClass.getName().hashCode();
    }

    public static final SyncedClassKey<AbstractArrow> ABSTRACT_ARROW = new SyncedClassKey<>(AbstractArrow.class, Identifier.withDefaultNamespace("abstract_arrow"));
    public static final SyncedClassKey<AbstractBoat> ABSTRACT_BOAT = new SyncedClassKey<>(AbstractBoat.class, Identifier.withDefaultNamespace("abstract_boat"));
    public static final SyncedClassKey<AbstractChestBoat> ABSTRACT_CHEST_BOAT = new SyncedClassKey<>(AbstractChestBoat.class, Identifier.withDefaultNamespace("abstract_chest_boat"));
    public static final SyncedClassKey<AbstractChestedHorse> ABSTRACT_CHESTED_HORSE = new SyncedClassKey<>(AbstractChestedHorse.class, Identifier.withDefaultNamespace("abstract_chested_horse"));
    public static final SyncedClassKey<AbstractCow> ABSTRACT_COW = new SyncedClassKey<>(AbstractCow.class, Identifier.withDefaultNamespace("abstract_cow"));
    public static final SyncedClassKey<AbstractFish> ABSTRACT_FISH = new SyncedClassKey<>(AbstractFish.class, Identifier.withDefaultNamespace("abstract_fish"));
    public static final SyncedClassKey<AbstractGolem> ABSTRACT_GOLEM = new SyncedClassKey<>(AbstractGolem.class, Identifier.withDefaultNamespace("abstract_golem"));
    public static final SyncedClassKey<AbstractHorse> ABSTRACT_HORSE = new SyncedClassKey<>(AbstractHorse.class, Identifier.withDefaultNamespace("abstract_horse"));
    public static final SyncedClassKey<AbstractHurtingProjectile> ABSTRACT_HURTING_PROJECTILE = new SyncedClassKey<>(AbstractHurtingProjectile.class, Identifier.withDefaultNamespace("abstract_hurting_projectile"));
    public static final SyncedClassKey<AbstractIllager> ABSTRACT_ILLAGER = new SyncedClassKey<>(AbstractIllager.class, Identifier.withDefaultNamespace("abstract_illager"));
    public static final SyncedClassKey<AbstractMinecart> ABSTRACT_MINECART = new SyncedClassKey<>(AbstractMinecart.class, Identifier.withDefaultNamespace("abstract_minecart"));
    public static final SyncedClassKey<AbstractMinecartContainer> ABSTRACT_MINECART_CONTAINER = new SyncedClassKey<>(AbstractMinecartContainer.class, Identifier.withDefaultNamespace("abstract_minecart_container"));
    public static final SyncedClassKey<AbstractPiglin> ABSTRACT_PIGLIN = new SyncedClassKey<>(AbstractPiglin.class, Identifier.withDefaultNamespace("abstract_piglin"));
    public static final SyncedClassKey<AbstractSchoolingFish> ABSTRACT_SCHOOLING_FISH = new SyncedClassKey<>(AbstractSchoolingFish.class, Identifier.withDefaultNamespace("abstract_schooling_fish"));
    public static final SyncedClassKey<AbstractSkeleton> ABSTRACT_SKELETON = new SyncedClassKey<>(AbstractSkeleton.class, Identifier.withDefaultNamespace("abstract_skeleton"));
    public static final SyncedClassKey<AbstractThrownPotion> ABSTRACT_THROWN_POTION = new SyncedClassKey<>(AbstractThrownPotion.class, Identifier.withDefaultNamespace("abstract_thrown_potion"));
    public static final SyncedClassKey<AbstractVillager> ABSTRACT_VILLAGER = new SyncedClassKey<>(AbstractVillager.class, Identifier.withDefaultNamespace("abstract_villager"));
    public static final SyncedClassKey<AbstractWindCharge> ABSTRACT_WIND_CHARGE = new SyncedClassKey<>(AbstractWindCharge.class, Identifier.withDefaultNamespace("abstract_wind_charge"));
    public static final SyncedClassKey<AgeableMob> AGEABLE_MOB = new SyncedClassKey<>(AgeableMob.class, Identifier.withDefaultNamespace("ageable_mob"));
    public static final SyncedClassKey<AgeableWaterCreature> AGEABLE_WATER_CREATURE = new SyncedClassKey<>(AgeableWaterCreature.class, Identifier.withDefaultNamespace("ageable_water_creature"));
    public static final SyncedClassKey<Allay> ALLAY = new SyncedClassKey<>(Allay.class, Identifier.withDefaultNamespace("allay"));
    public static final SyncedClassKey<AmbientCreature> AMBIENT_CREATURE = new SyncedClassKey<>(AmbientCreature.class, Identifier.withDefaultNamespace("ambient_creature"));
    public static final SyncedClassKey<Animal> ANIMAL = new SyncedClassKey<>(Animal.class, Identifier.withDefaultNamespace("animal"));
    public static final SyncedClassKey<AreaEffectCloud> AREA_EFFECT_CLOUD = new SyncedClassKey<>(AreaEffectCloud.class, Identifier.withDefaultNamespace("area_effect_cloud"));
    public static final SyncedClassKey<Armadillo> ARMADILLO = new SyncedClassKey<>(Armadillo.class, Identifier.withDefaultNamespace("armadillo"));
    public static final SyncedClassKey<ArmorStand> ARMOR_STAND = new SyncedClassKey<>(ArmorStand.class, Identifier.withDefaultNamespace("armor_stand"));
    public static final SyncedClassKey<Arrow> ARROW = new SyncedClassKey<>(Arrow.class, Identifier.withDefaultNamespace("arrow"));
    public static final SyncedClassKey<Axolotl> AXOLOTL = new SyncedClassKey<>(Axolotl.class, Identifier.withDefaultNamespace("axolotl"));
    public static final SyncedClassKey<Bat> BAT = new SyncedClassKey<>(Bat.class, Identifier.withDefaultNamespace("bat"));
    public static final SyncedClassKey<Bee> BEE = new SyncedClassKey<>(Bee.class, Identifier.withDefaultNamespace("bee"));
    public static final SyncedClassKey<Blaze> BLAZE = new SyncedClassKey<>(Blaze.class, Identifier.withDefaultNamespace("blaze"));
    public static final SyncedClassKey<BlockAttachedEntity> BLOCK_ATTACHED_ENTITY = new SyncedClassKey<>(BlockAttachedEntity.class, Identifier.withDefaultNamespace("block_attached_entity"));
    public static final SyncedClassKey<Display.BlockDisplay> BLOCK_DISPLAY_IN_DISPLAY = new SyncedClassKey<>(Display.BlockDisplay.class, Identifier.withDefaultNamespace("block_display_in_display"));
    public static final SyncedClassKey<Boat> BOAT = new SyncedClassKey<>(Boat.class, Identifier.withDefaultNamespace("boat"));
    public static final SyncedClassKey<Bogged> BOGGED = new SyncedClassKey<>(Bogged.class, Identifier.withDefaultNamespace("bogged"));
    public static final SyncedClassKey<Breeze> BREEZE = new SyncedClassKey<>(Breeze.class, Identifier.withDefaultNamespace("breeze"));
    public static final SyncedClassKey<BreezeWindCharge> BREEZE_WIND_CHARGE = new SyncedClassKey<>(BreezeWindCharge.class, Identifier.withDefaultNamespace("breeze_wind_charge"));
    public static final SyncedClassKey<Camel> CAMEL = new SyncedClassKey<>(Camel.class, Identifier.withDefaultNamespace("camel"));
    public static final SyncedClassKey<Cat> CAT = new SyncedClassKey<>(Cat.class, Identifier.withDefaultNamespace("cat"));
    public static final SyncedClassKey<CaveSpider> CAVE_SPIDER = new SyncedClassKey<>(CaveSpider.class, Identifier.withDefaultNamespace("cave_spider"));
    public static final SyncedClassKey<ChestBoat> CHEST_BOAT = new SyncedClassKey<>(ChestBoat.class, Identifier.withDefaultNamespace("chest_boat"));
    public static final SyncedClassKey<ChestRaft> CHEST_RAFT = new SyncedClassKey<>(ChestRaft.class, Identifier.withDefaultNamespace("chest_raft"));
    public static final SyncedClassKey<Chicken> CHICKEN = new SyncedClassKey<>(Chicken.class, Identifier.withDefaultNamespace("chicken"));
    public static final SyncedClassKey<Cod> COD = new SyncedClassKey<>(Cod.class, Identifier.withDefaultNamespace("cod"));
    public static final SyncedClassKey<Cow> COW = new SyncedClassKey<>(Cow.class, Identifier.withDefaultNamespace("cow"));
    public static final SyncedClassKey<Creaking> CREAKING = new SyncedClassKey<>(Creaking.class, Identifier.withDefaultNamespace("creaking"));
    public static final SyncedClassKey<Creeper> CREEPER = new SyncedClassKey<>(Creeper.class, Identifier.withDefaultNamespace("creeper"));
    public static final SyncedClassKey<Display> DISPLAY = new SyncedClassKey<>(Display.class, Identifier.withDefaultNamespace("display"));
    public static final SyncedClassKey<Dolphin> DOLPHIN = new SyncedClassKey<>(Dolphin.class, Identifier.withDefaultNamespace("dolphin"));
    public static final SyncedClassKey<Donkey> DONKEY = new SyncedClassKey<>(Donkey.class, Identifier.withDefaultNamespace("donkey"));
    public static final SyncedClassKey<DragonFireball> DRAGON_FIREBALL = new SyncedClassKey<>(DragonFireball.class, Identifier.withDefaultNamespace("dragon_fireball"));
    public static final SyncedClassKey<Drowned> DROWNED = new SyncedClassKey<>(Drowned.class, Identifier.withDefaultNamespace("drowned"));
    public static final SyncedClassKey<ElderGuardian> ELDER_GUARDIAN = new SyncedClassKey<>(ElderGuardian.class, Identifier.withDefaultNamespace("elder_guardian"));
    public static final SyncedClassKey<EndCrystal> END_CRYSTAL = new SyncedClassKey<>(EndCrystal.class, Identifier.withDefaultNamespace("end_crystal"));
    public static final SyncedClassKey<EnderDragon> ENDER_DRAGON = new SyncedClassKey<>(EnderDragon.class, Identifier.withDefaultNamespace("ender_dragon"));
    public static final SyncedClassKey<EnderMan> ENDER_MAN = new SyncedClassKey<>(EnderMan.class, Identifier.withDefaultNamespace("ender_man"));
    public static final SyncedClassKey<Endermite> ENDERMITE = new SyncedClassKey<>(Endermite.class, Identifier.withDefaultNamespace("endermite"));
    public static final SyncedClassKey<Evoker> EVOKER = new SyncedClassKey<>(Evoker.class, Identifier.withDefaultNamespace("evoker"));
    public static final SyncedClassKey<EvokerFangs> EVOKER_FANGS = new SyncedClassKey<>(EvokerFangs.class, Identifier.withDefaultNamespace("evoker_fangs"));
    public static final SyncedClassKey<ExperienceOrb> EXPERIENCE_ORB = new SyncedClassKey<>(ExperienceOrb.class, Identifier.withDefaultNamespace("experience_orb"));
    public static final SyncedClassKey<EyeOfEnder> EYE_OF_ENDER = new SyncedClassKey<>(EyeOfEnder.class, Identifier.withDefaultNamespace("eye_of_ender"));
    public static final SyncedClassKey<FallingBlockEntity> FALLING_BLOCK_ENTITY = new SyncedClassKey<>(FallingBlockEntity.class, Identifier.withDefaultNamespace("falling_block_entity"));
    public static final SyncedClassKey<Fireball> FIREBALL = new SyncedClassKey<>(Fireball.class, Identifier.withDefaultNamespace("fireball"));
    public static final SyncedClassKey<FireworkRocketEntity> FIREWORK_ROCKET_ENTITY = new SyncedClassKey<>(FireworkRocketEntity.class, Identifier.withDefaultNamespace("firework_rocket_entity"));
    public static final SyncedClassKey<FishingHook> FISHING_HOOK = new SyncedClassKey<>(FishingHook.class, Identifier.withDefaultNamespace("fishing_hook"));
    public static final SyncedClassKey<Fox> FOX = new SyncedClassKey<>(Fox.class, Identifier.withDefaultNamespace("fox"));
    public static final SyncedClassKey<Frog> FROG = new SyncedClassKey<>(Frog.class, Identifier.withDefaultNamespace("frog"));
    public static final SyncedClassKey<Ghast> GHAST = new SyncedClassKey<>(Ghast.class, Identifier.withDefaultNamespace("ghast"));
    public static final SyncedClassKey<Giant> GIANT = new SyncedClassKey<>(Giant.class, Identifier.withDefaultNamespace("giant"));
    public static final SyncedClassKey<GlowItemFrame> GLOW_ITEM_FRAME = new SyncedClassKey<>(GlowItemFrame.class, Identifier.withDefaultNamespace("glow_item_frame"));
    public static final SyncedClassKey<GlowSquid> GLOW_SQUID = new SyncedClassKey<>(GlowSquid.class, Identifier.withDefaultNamespace("glow_squid"));
    public static final SyncedClassKey<Goat> GOAT = new SyncedClassKey<>(Goat.class, Identifier.withDefaultNamespace("goat"));
    public static final SyncedClassKey<Guardian> GUARDIAN = new SyncedClassKey<>(Guardian.class, Identifier.withDefaultNamespace("guardian"));
    public static final SyncedClassKey<HangingEntity> HANGING_ENTITY = new SyncedClassKey<>(HangingEntity.class, Identifier.withDefaultNamespace("hanging_entity"));
    public static final SyncedClassKey<HappyGhast> HAPPY_GHAST = new SyncedClassKey<>(HappyGhast.class, Identifier.withDefaultNamespace("happy_ghast"));
    public static final SyncedClassKey<Hoglin> HOGLIN = new SyncedClassKey<>(Hoglin.class, Identifier.withDefaultNamespace("hoglin"));
    public static final SyncedClassKey<Horse> HORSE = new SyncedClassKey<>(Horse.class, Identifier.withDefaultNamespace("horse"));
    public static final SyncedClassKey<Husk> HUSK = new SyncedClassKey<>(Husk.class, Identifier.withDefaultNamespace("husk"));
    public static final SyncedClassKey<Illusioner> ILLUSIONER = new SyncedClassKey<>(Illusioner.class, Identifier.withDefaultNamespace("illusioner"));
    public static final SyncedClassKey<Interaction> INTERACTION = new SyncedClassKey<>(Interaction.class, Identifier.withDefaultNamespace("interaction"));
    public static final SyncedClassKey<IronGolem> IRON_GOLEM = new SyncedClassKey<>(IronGolem.class, Identifier.withDefaultNamespace("iron_golem"));
    public static final SyncedClassKey<Display.ItemDisplay> ITEM_DISPLAY_IN_DISPLAY = new SyncedClassKey<>(Display.ItemDisplay.class, Identifier.withDefaultNamespace("item_display_in_display"));
    public static final SyncedClassKey<ItemEntity> ITEM_ENTITY = new SyncedClassKey<>(ItemEntity.class, Identifier.withDefaultNamespace("item_entity"));
    public static final SyncedClassKey<ItemFrame> ITEM_FRAME = new SyncedClassKey<>(ItemFrame.class, Identifier.withDefaultNamespace("item_frame"));
    public static final SyncedClassKey<LargeFireball> LARGE_FIREBALL = new SyncedClassKey<>(LargeFireball.class, Identifier.withDefaultNamespace("large_fireball"));
    public static final SyncedClassKey<LeashFenceKnotEntity> LEASH_FENCE_KNOT_ENTITY = new SyncedClassKey<>(LeashFenceKnotEntity.class, Identifier.withDefaultNamespace("leash_fence_knot_entity"));
    public static final SyncedClassKey<LightningBolt> LIGHTNING_BOLT = new SyncedClassKey<>(LightningBolt.class, Identifier.withDefaultNamespace("lightning_bolt"));
    public static final SyncedClassKey<LivingEntity> LIVING_ENTITY = new SyncedClassKey<>(LivingEntity.class, Identifier.withDefaultNamespace("living_entity"));
    public static final SyncedClassKey<Llama> LLAMA = new SyncedClassKey<>(Llama.class, Identifier.withDefaultNamespace("llama"));
    public static final SyncedClassKey<LlamaSpit> LLAMA_SPIT = new SyncedClassKey<>(LlamaSpit.class, Identifier.withDefaultNamespace("llama_spit"));
    public static final SyncedClassKey<MagmaCube> MAGMA_CUBE = new SyncedClassKey<>(MagmaCube.class, Identifier.withDefaultNamespace("magma_cube"));
    public static final SyncedClassKey<Marker> MARKER = new SyncedClassKey<>(Marker.class, Identifier.withDefaultNamespace("marker"));
    public static final SyncedClassKey<Minecart> MINECART = new SyncedClassKey<>(Minecart.class, Identifier.withDefaultNamespace("minecart"));
    public static final SyncedClassKey<MinecartChest> MINECART_CHEST = new SyncedClassKey<>(MinecartChest.class, Identifier.withDefaultNamespace("minecart_chest"));
    public static final SyncedClassKey<MinecartCommandBlock> MINECART_COMMAND_BLOCK = new SyncedClassKey<>(MinecartCommandBlock.class, Identifier.withDefaultNamespace("minecart_command_block"));
    public static final SyncedClassKey<MinecartFurnace> MINECART_FURNACE = new SyncedClassKey<>(MinecartFurnace.class, Identifier.withDefaultNamespace("minecart_furnace"));
    public static final SyncedClassKey<MinecartHopper> MINECART_HOPPER = new SyncedClassKey<>(MinecartHopper.class, Identifier.withDefaultNamespace("minecart_hopper"));
    public static final SyncedClassKey<MinecartSpawner> MINECART_SPAWNER = new SyncedClassKey<>(MinecartSpawner.class, Identifier.withDefaultNamespace("minecart_spawner"));
    public static final SyncedClassKey<MinecartTNT> MINECART_TNT = new SyncedClassKey<>(MinecartTNT.class, Identifier.withDefaultNamespace("minecart_tnt"));
    public static final SyncedClassKey<Mob> MOB = new SyncedClassKey<>(Mob.class, Identifier.withDefaultNamespace("mob"));
    public static final SyncedClassKey<Monster> MONSTER = new SyncedClassKey<>(Monster.class, Identifier.withDefaultNamespace("monster"));
    public static final SyncedClassKey<Mule> MULE = new SyncedClassKey<>(Mule.class, Identifier.withDefaultNamespace("mule"));
    public static final SyncedClassKey<MushroomCow> MUSHROOM_COW = new SyncedClassKey<>(MushroomCow.class, Identifier.withDefaultNamespace("mushroom_cow"));
    public static final SyncedClassKey<Ocelot> OCELOT = new SyncedClassKey<>(Ocelot.class, Identifier.withDefaultNamespace("ocelot"));
    public static final SyncedClassKey<OminousItemSpawner> OMINOUS_ITEM_SPAWNER = new SyncedClassKey<>(OminousItemSpawner.class, Identifier.withDefaultNamespace("ominous_item_spawner"));
    public static final SyncedClassKey<Painting> PAINTING = new SyncedClassKey<>(Painting.class, Identifier.withDefaultNamespace("painting"));
    public static final SyncedClassKey<Panda> PANDA = new SyncedClassKey<>(Panda.class, Identifier.withDefaultNamespace("panda"));
    public static final SyncedClassKey<Parrot> PARROT = new SyncedClassKey<>(Parrot.class, Identifier.withDefaultNamespace("parrot"));
    public static final SyncedClassKey<PathfinderMob> PATHFINDER_MOB = new SyncedClassKey<>(PathfinderMob.class, Identifier.withDefaultNamespace("pathfinder_mob"));
    public static final SyncedClassKey<PatrollingMonster> PATROLLING_MONSTER = new SyncedClassKey<>(PatrollingMonster.class, Identifier.withDefaultNamespace("patrolling_monster"));
    public static final SyncedClassKey<Phantom> PHANTOM = new SyncedClassKey<>(Phantom.class, Identifier.withDefaultNamespace("phantom"));
    public static final SyncedClassKey<Pig> PIG = new SyncedClassKey<>(Pig.class, Identifier.withDefaultNamespace("pig"));
    public static final SyncedClassKey<Piglin> PIGLIN = new SyncedClassKey<>(Piglin.class, Identifier.withDefaultNamespace("piglin"));
    public static final SyncedClassKey<PiglinBrute> PIGLIN_BRUTE = new SyncedClassKey<>(PiglinBrute.class, Identifier.withDefaultNamespace("piglin_brute"));
    public static final SyncedClassKey<Pillager> PILLAGER = new SyncedClassKey<>(Pillager.class, Identifier.withDefaultNamespace("pillager"));
    public static final SyncedClassKey<Player> PLAYER = new SyncedClassKey<>(Player.class, Identifier.withDefaultNamespace("player"));
    public static final SyncedClassKey<PolarBear> POLAR_BEAR = new SyncedClassKey<>(PolarBear.class, Identifier.withDefaultNamespace("polar_bear"));
    public static final SyncedClassKey<PrimedTnt> PRIMED_TNT = new SyncedClassKey<>(PrimedTnt.class, Identifier.withDefaultNamespace("primed_tnt"));
    public static final SyncedClassKey<Projectile> PROJECTILE = new SyncedClassKey<>(Projectile.class, Identifier.withDefaultNamespace("projectile"));
    public static final SyncedClassKey<Pufferfish> PUFFERFISH = new SyncedClassKey<>(Pufferfish.class, Identifier.withDefaultNamespace("pufferfish"));
    public static final SyncedClassKey<Rabbit> RABBIT = new SyncedClassKey<>(Rabbit.class, Identifier.withDefaultNamespace("rabbit"));
    public static final SyncedClassKey<Raft> RAFT = new SyncedClassKey<>(Raft.class, Identifier.withDefaultNamespace("raft"));
    public static final SyncedClassKey<Raider> RAIDER = new SyncedClassKey<>(Raider.class, Identifier.withDefaultNamespace("raider"));
    public static final SyncedClassKey<Ravager> RAVAGER = new SyncedClassKey<>(Ravager.class, Identifier.withDefaultNamespace("ravager"));
    public static final SyncedClassKey<Salmon> SALMON = new SyncedClassKey<>(Salmon.class, Identifier.withDefaultNamespace("salmon"));
    public static final SyncedClassKey<Sheep> SHEEP = new SyncedClassKey<>(Sheep.class, Identifier.withDefaultNamespace("sheep"));
    public static final SyncedClassKey<ShoulderRidingEntity> SHOULDER_RIDING_ENTITY = new SyncedClassKey<>(ShoulderRidingEntity.class, Identifier.withDefaultNamespace("shoulder_riding_entity"));
    public static final SyncedClassKey<Shulker> SHULKER = new SyncedClassKey<>(Shulker.class, Identifier.withDefaultNamespace("shulker"));
    public static final SyncedClassKey<ShulkerBullet> SHULKER_BULLET = new SyncedClassKey<>(ShulkerBullet.class, Identifier.withDefaultNamespace("shulker_bullet"));
    public static final SyncedClassKey<Silverfish> SILVERFISH = new SyncedClassKey<>(Silverfish.class, Identifier.withDefaultNamespace("silverfish"));
    public static final SyncedClassKey<Skeleton> SKELETON = new SyncedClassKey<>(Skeleton.class, Identifier.withDefaultNamespace("skeleton"));
    public static final SyncedClassKey<SkeletonHorse> SKELETON_HORSE = new SyncedClassKey<>(SkeletonHorse.class, Identifier.withDefaultNamespace("skeleton_horse"));
    public static final SyncedClassKey<Slime> SLIME = new SyncedClassKey<>(Slime.class, Identifier.withDefaultNamespace("slime"));
    public static final SyncedClassKey<SmallFireball> SMALL_FIREBALL = new SyncedClassKey<>(SmallFireball.class, Identifier.withDefaultNamespace("small_fireball"));
    public static final SyncedClassKey<Sniffer> SNIFFER = new SyncedClassKey<>(Sniffer.class, Identifier.withDefaultNamespace("sniffer"));
    public static final SyncedClassKey<SnowGolem> SNOW_GOLEM = new SyncedClassKey<>(SnowGolem.class, Identifier.withDefaultNamespace("snow_golem"));
    public static final SyncedClassKey<Snowball> SNOWBALL = new SyncedClassKey<>(Snowball.class, Identifier.withDefaultNamespace("snowball"));
    public static final SyncedClassKey<SpectralArrow> SPECTRAL_ARROW = new SyncedClassKey<>(SpectralArrow.class, Identifier.withDefaultNamespace("spectral_arrow"));
    public static final SyncedClassKey<SpellcasterIllager> SPELLCASTER_ILLAGER = new SyncedClassKey<>(SpellcasterIllager.class, Identifier.withDefaultNamespace("spellcaster_illager"));
    public static final SyncedClassKey<Spider> SPIDER = new SyncedClassKey<>(Spider.class, Identifier.withDefaultNamespace("spider"));
    public static final SyncedClassKey<Squid> SQUID = new SyncedClassKey<>(Squid.class, Identifier.withDefaultNamespace("squid"));
    public static final SyncedClassKey<Stray> STRAY = new SyncedClassKey<>(Stray.class, Identifier.withDefaultNamespace("stray"));
    public static final SyncedClassKey<Strider> STRIDER = new SyncedClassKey<>(Strider.class, Identifier.withDefaultNamespace("strider"));
    public static final SyncedClassKey<Tadpole> TADPOLE = new SyncedClassKey<>(Tadpole.class, Identifier.withDefaultNamespace("tadpole"));
    public static final SyncedClassKey<TamableAnimal> TAMABLE_ANIMAL = new SyncedClassKey<>(TamableAnimal.class, Identifier.withDefaultNamespace("tamable_animal"));
    public static final SyncedClassKey<Display.TextDisplay> TEXT_DISPLAY_IN_DISPLAY = new SyncedClassKey<>(Display.TextDisplay.class, Identifier.withDefaultNamespace("text_display_in_display"));
    public static final SyncedClassKey<ThrowableItemProjectile> THROWABLE_ITEM_PROJECTILE = new SyncedClassKey<>(ThrowableItemProjectile.class, Identifier.withDefaultNamespace("throwable_item_projectile"));
    public static final SyncedClassKey<ThrowableProjectile> THROWABLE_PROJECTILE = new SyncedClassKey<>(ThrowableProjectile.class, Identifier.withDefaultNamespace("throwable_projectile"));
    public static final SyncedClassKey<ThrownEgg> THROWN_EGG = new SyncedClassKey<>(ThrownEgg.class, Identifier.withDefaultNamespace("thrown_egg"));
    public static final SyncedClassKey<ThrownEnderpearl> THROWN_ENDERPEARL = new SyncedClassKey<>(ThrownEnderpearl.class, Identifier.withDefaultNamespace("thrown_enderpearl"));
    public static final SyncedClassKey<ThrownExperienceBottle> THROWN_EXPERIENCE_BOTTLE = new SyncedClassKey<>(ThrownExperienceBottle.class, Identifier.withDefaultNamespace("thrown_experience_bottle"));
    public static final SyncedClassKey<ThrownLingeringPotion> THROWN_LINGERING_POTION = new SyncedClassKey<>(ThrownLingeringPotion.class, Identifier.withDefaultNamespace("thrown_lingering_potion"));
    public static final SyncedClassKey<ThrownSplashPotion> THROWN_SPLASH_POTION = new SyncedClassKey<>(ThrownSplashPotion.class, Identifier.withDefaultNamespace("thrown_splash_potion"));
    public static final SyncedClassKey<ThrownTrident> THROWN_TRIDENT = new SyncedClassKey<>(ThrownTrident.class, Identifier.withDefaultNamespace("thrown_trident"));
    public static final SyncedClassKey<TraderLlama> TRADER_LLAMA = new SyncedClassKey<>(TraderLlama.class, Identifier.withDefaultNamespace("trader_llama"));
    public static final SyncedClassKey<TropicalFish> TROPICAL_FISH = new SyncedClassKey<>(TropicalFish.class, Identifier.withDefaultNamespace("tropical_fish"));
    public static final SyncedClassKey<Turtle> TURTLE = new SyncedClassKey<>(Turtle.class, Identifier.withDefaultNamespace("turtle"));
    public static final SyncedClassKey<VehicleEntity> VEHICLE_ENTITY = new SyncedClassKey<>(VehicleEntity.class, Identifier.withDefaultNamespace("vehicle_entity"));
    public static final SyncedClassKey<Vex> VEX = new SyncedClassKey<>(Vex.class, Identifier.withDefaultNamespace("vex"));
    public static final SyncedClassKey<Villager> VILLAGER = new SyncedClassKey<>(Villager.class, Identifier.withDefaultNamespace("villager"));
    public static final SyncedClassKey<Vindicator> VINDICATOR = new SyncedClassKey<>(Vindicator.class, Identifier.withDefaultNamespace("vindicator"));
    public static final SyncedClassKey<WanderingTrader> WANDERING_TRADER = new SyncedClassKey<>(WanderingTrader.class, Identifier.withDefaultNamespace("wandering_trader"));
    public static final SyncedClassKey<Warden> WARDEN = new SyncedClassKey<>(Warden.class, Identifier.withDefaultNamespace("warden"));
    public static final SyncedClassKey<WaterAnimal> WATER_ANIMAL = new SyncedClassKey<>(WaterAnimal.class, Identifier.withDefaultNamespace("water_animal"));
    public static final SyncedClassKey<WindCharge> WIND_CHARGE = new SyncedClassKey<>(WindCharge.class, Identifier.withDefaultNamespace("wind_charge"));
    public static final SyncedClassKey<Witch> WITCH = new SyncedClassKey<>(Witch.class, Identifier.withDefaultNamespace("witch"));
    public static final SyncedClassKey<WitherBoss> WITHER_BOSS = new SyncedClassKey<>(WitherBoss.class, Identifier.withDefaultNamespace("wither_boss"));
    public static final SyncedClassKey<WitherSkeleton> WITHER_SKELETON = new SyncedClassKey<>(WitherSkeleton.class, Identifier.withDefaultNamespace("wither_skeleton"));
    public static final SyncedClassKey<WitherSkull> WITHER_SKULL = new SyncedClassKey<>(WitherSkull.class, Identifier.withDefaultNamespace("wither_skull"));
    public static final SyncedClassKey<Wolf> WOLF = new SyncedClassKey<>(Wolf.class, Identifier.withDefaultNamespace("wolf"));
    public static final SyncedClassKey<Zoglin> ZOGLIN = new SyncedClassKey<>(Zoglin.class, Identifier.withDefaultNamespace("zoglin"));
    public static final SyncedClassKey<Zombie> ZOMBIE = new SyncedClassKey<>(Zombie.class, Identifier.withDefaultNamespace("zombie"));
    public static final SyncedClassKey<ZombieHorse> ZOMBIE_HORSE = new SyncedClassKey<>(ZombieHorse.class, Identifier.withDefaultNamespace("zombie_horse"));
    public static final SyncedClassKey<ZombieVillager> ZOMBIE_VILLAGER = new SyncedClassKey<>(ZombieVillager.class, Identifier.withDefaultNamespace("zombie_villager"));
    public static final SyncedClassKey<ZombifiedPiglin> ZOMBIFIED_PIGLIN = new SyncedClassKey<>(ZombifiedPiglin.class, Identifier.withDefaultNamespace("zombified_piglin"));
}
